[package]
name = "horizonos-graph-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
horizonos-graph-engine = { path = "../graph-engine" }
horizonos-graph-nodes = { path = "../graph-nodes" }
serde = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
