[package]
name = "aios-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "aiosctl"
path = "src/main.rs"

[dependencies]
aios-protocol = { path = "../aios-protocol" }
aios-system = { path = "../aios-system" }
serde_json = "1.0"
aios-session = { path = "../aios-session" }
