[package]
name = "horizonos-graph-interaction"
version = "0.1.0"
edition = "2021"

[dependencies]
horizonos-graph-engine = { path = "../graph-engine" }
serde = { workspace = true }
tokio = { workspace = true }
