# Independent installed authority is generated by the administrator-owned flake.
{ aiosTemplate, ... }:
{
  environment.etc."aios/template-authority.json" = {
    mode = "0444";
    text = builtins.toJSON (aiosTemplate.authority // { template_path = "${aiosTemplate}"; });
  };
  systemd.tmpfiles.rules = [
    "d /var/lib/aios 0755 root root -"
    "d /var/lib/aios/candidates 0755 root root -"
    "d /var/lib/aios/transactions 0700 root root -"
  ];
}
