# Independent installed authority is generated by the administrator-owned flake.
{ config, lib, aiosTemplate, aiosExecutor, ... }:
{
  environment.etc."aios/template-authority.json" = {
    mode = "0444";
    text = builtins.toJSON (aiosTemplate.authority // { template_path = "${aiosTemplate}"; });
  };
  environment.etc."aios/journal-readers.json" = {
    mode = "0444";
    text = builtins.toJSON {
      schema_version = 1;
      users = builtins.filter (name: config.users.users.${name}.isNormalUser)
        (builtins.attrNames config.users.users);
    };
  };
  security.polkit.enable = true;
  # polkit 127's socket-activated helper cannot complete stock pam_unix
  # authentication (upstream #695). Mask that socket and retain the standard
  # setuid helper until the pinned package carries the upstream fix.
  systemd.sockets.polkit-agent-helper.enable = lib.mkForce false;
  security.wrappers."polkit-agent-helper-1" = {
    source = "${config.security.polkit.package.out}/lib/polkit-1/polkit-agent-helper-1";
    owner = "root";
    group = "root";
    setuid = true;
  };
  environment.systemPackages = [ aiosExecutor ];
  services.dbus.packages = [ aiosExecutor ];
  systemd.packages = [ aiosExecutor ];
  users.groups.aios-builder = {};
  users.users.aios-builder = {
    isSystemUser = true;
    group = "aios-builder";
    home = "/var/empty";
  };
  systemd.services.aios-execd = {
    wantedBy = [ "multi-user.target" ];
    overrideStrategy = "asDropin";
  };
  systemd.services.aios-build = {
    wantedBy = [ "multi-user.target" ];
    overrideStrategy = "asDropin";
  };
  environment.etc."aios/approval-authority.json" = {
    mode = "0444";
    text = builtins.toJSON {
      schema_version = 1;
      policy_path = "${aiosExecutor}/share/aios/system-approval.json";
      policy_sha256 = builtins.hashFile "sha256" ../../../crates/aios-exec/policy/system-approval.json;
      action_path = "${aiosExecutor}/share/polkit-1/actions/org.aios.executor.policy";
      action_sha256 = builtins.hashFile "sha256" ../../../crates/aios-exec/policy/org.aios.executor.policy;
      polkit_uid = config.users.users.polkituser.uid;
      polkit_package = "${config.security.polkit.package.out}";
    };
  };
  assertions = [
    {
      assertion = !config.security.polkit.debug;
      message = "Horizon OS does not permit polkit debug logging in its approval configuration.";
    }
    {
      assertion = config.nix.settings.trusted-users == [ "root" ];
      message = "Candidate builds require root to remain the only Nix trusted-user.";
    }
  ];
  systemd.tmpfiles.rules = [
    "d /var/lib/aios 0755 root root -"
    "d /var/lib/aios/candidates 0755 root root -"
    "d /var/lib/aios/transactions 0700 root root -"
  ];
}
