# Independent installed authority is generated by the administrator-owned flake.
{ config, aiosTemplate, aiosExecutor, ... }:
{
  environment.etc."aios/template-authority.json" = {
    mode = "0444";
    text = builtins.toJSON (aiosTemplate.authority // { template_path = "${aiosTemplate}"; });
  };
  environment.etc."aios/journal-readers.json" = {
    mode = "0444";
    text = builtins.toJSON {
      schema_version = 1;
      users = builtins.filter (name: config.users.users.${name}.isNormalUser)
        (builtins.attrNames config.users.users);
    };
  };
  security.polkit.enable = true;
  environment.systemPackages = [ aiosExecutor ];
  services.dbus.packages = [ aiosExecutor ];
  systemd.packages = [ aiosExecutor ];
  systemd.services.aios-execd = {
    wantedBy = [ "multi-user.target" ];
    overrideStrategy = "asDropin";
  };
  environment.etc."aios/approval-authority.json" = {
    mode = "0444";
    text = builtins.toJSON {
      schema_version = 1;
      policy_path = "${aiosExecutor}/share/aios/system-approval.json";
      policy_sha256 = builtins.hashFile "sha256" ../../../crates/aios-exec/policy/system-approval.json;
      action_path = "${aiosExecutor}/share/polkit-1/actions/org.aios.executor.policy";
      action_sha256 = builtins.hashFile "sha256" ../../../crates/aios-exec/policy/org.aios.executor.policy;
      polkit_uid = config.users.users.polkituser.uid;
      polkit_package = "${config.security.polkit.package.out}";
    };
  };
  assertions = [{
    assertion = !config.security.polkit.debug;
    message = "Horizon OS does not permit polkit debug logging in its approval configuration.";
  }];
  systemd.tmpfiles.rules = [
    "d /var/lib/aios 0755 root root -"
    "d /var/lib/aios/candidates 0755 root root -"
    "d /var/lib/aios/transactions 0700 root root -"
  ];
}
